// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deleteChirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirpById = `-- name: DeleteChirpById :one
delete from chirps
where id = $1
RETURNING id, created_at, updated_at, body, user_id
`

func (q *Queries) DeleteChirpById(ctx context.Context, id uuid.UUID) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, deleteChirpById, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.UserID,
	)
	return i, err
}
