// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: storerefresh.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const storeRefreshToken = `-- name: StoreRefreshToken :one
INSERT into refresh_tokens
(token, created_at, updated_at, user_id, expires_at)
VALUES
($1, $2, $2, $3, $4)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type StoreRefreshTokenParams struct {
	Token     string
	CreatedAt sql.NullTime
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, storeRefreshToken,
		arg.Token,
		arg.CreatedAt,
		arg.UserID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
